#pragma once

#define IMAGESIZE_X 145
#define IMAGESIZE_Y 235

#define NO_INDEX -5
#define NUMBER_OF_PAIR 5
#define INCORRECT_TIME 3

#define CARD_MAX 10

enum CARD_LOCATION
{
	CARD_LOCATION_FIRST_X = 20,
	CARD_LOCATION_FIRST_Y = 50,
	CARD_LOCATION_SECOND_X = 180,
	CARD_LOCATION_SECOND_Y = 50,
	CARD_LOCATION_THIRD_X = 340,
	CARD_LOCATION_THIRD_Y = 50,
	CARD_LOCATION_FOURTH_X = 500,
	CARD_LOCATION_FOURTH_Y = 50,
	CARD_LOCATION_FIFTH_X = 660,
	CARD_LOCATION_FIFTH_Y = 50,
	CARD_LOCATION_SIXTH_X = 20,
	CARD_LOCATION_SIXTH_Y = 350,
	CARD_LOCATION_SEVENTH_X = 180,
	CARD_LOCATION_SEVENTH_Y = 350,
	CARD_LOCATION_EIGHTH_X = 340,
	CARD_LOCATION_EIGHTH_Y = 350,
	CARD_LOCATION_NINETH_X = 500,
	CARD_LOCATION_NINETH_Y = 350,
	CARD_LOCATION_TENTH_X = 660,
	CARD_LOCATION_TENTH_Y = 350
};

enum CARD_PICTURE
{
	CARD_PICTURE_BLANK = 0,
	CARD_PICTURE_FIRST = 1,
	CARD_PICTURE_SECOND = 2,
	CARD_PICTURE_THIRD = 3,
	CARD_PICTURE_FOURTH = 4,
	CARD_PICTURE_FIFTH = 5
};